### ISSUE TITLE
-f  freshen existing files, create none ?

### ISSUE THREAD

**Issue by geoffwright240** [Tallyrald/grocy-install#1]
Hi, I am just working my way through your excellent instructions for running grocy on a Google instance. First off, thank you for the writeup!

When you unzip the latest release of grocy, you have a -f flag set and I am wondering if this is correct. The documentation for the -f flag seems to suggest that it will not "create" files unless they are already there.

unzip --help
-f  freshen existing files, create none 

I am using the following instance:

Linux instance-grocy-1 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021 x86_64 x86_64 x86_64 GNU
/Linux

Is there a reason you are using the -f flag that I am missing? If not, would you accept a PR?

Thanks,

Geoff

**Comment by Tallyrald** [comment]
Hi Geoff!

You're completely correct, it seems I mistakenly left that flag in while repeatedly testing the script. Good catch!

It's an easy fix, no need for a PR. Thanks for bringing this to my attention.
