### ISSUE TITLE
New system requirements for installing the Grocy

### ISSUE THREAD

**Issue by Janovlk** [Tallyrald/grocy-install#2]
Hello,

thank you for your script. Now, from version 4 Grocy needs **PHP Version 8.1** or higher. (https://demo-prerelease.grocy.info/about?embedded) Be so kind, please, and update your script to download higher version of PHP. I can modify the main script by myself after downloading it to a new Linux installation, but it downloads another your scripts afterwards which I can't then modify.

Thank you,

PP

**Comment by Tallyrald** [comment]
Thanks for letting me know! I've updated the script to use PHP 8.2 instead of 8.0, can you please check if it works? I don't currently have the time to extensively test this, but I'll try my best to help if something is still not OK.

**Comment by Janovlk** [comment]
Thank you,
I tested it in Google Cloud using Ubuntu 22.04 LTS. Everything went okay, Grocy works. I'll test it once again in Ubuntu 23.04.
PP

**Comment by Janovlk** [comment]
As I learned, PHP packages from ppa:ondrej/php are created and maintained for LTS versions only so the Ubuntu 23.04 can't be used here.
Thank you for your work.

**Comment by Tallyrald** [comment]
Glad it worked :)

**Comment by declanhucdconnect** [comment]
Just to say that I've followed the original instructions (ubuntu-2004-lts) and see the following:
'Unable to run Grocy: SQLite 3.34.0 is required, however you are running 3.31.1'

I'll try with Ubuntu 22.04LTS and see what happens.

I'm Linux illiterate, so it may be my following of the instructions that the problem !  ;-)

**Comment by Janovlk** [comment]
Hi, as I mentioned in my previous post, in Ubuntu 22.04 LTS everything works.

**Comment by declanhucdconnect** [comment]
Yes - 22.04 works perfectly - needed to do a few service restarts during the install step on GCP, but all good now.
May be worth updating the doc to reflect the change.

( Thanks for the response )

**Comment by Tallyrald** [comment]
Thanks guys, I've updated both the README and the Reddit post to require Ubuntu 22.04 instead of 20.04.
